backend:
  name: github
  repo: feizi521/New-repository
  branch: main
  site_domain: tuji.farholme.com

media_folder: "uploads"
public_folder: "/"
media_library:
  name: cloudinary
  config:
    cloud_name: "demo"
    api_key: "874837483274837"
    default_transformations: [{quality: "auto"}]

collections:
  - name: "wallpaper"
    label: "高清壁纸"
    folder: "_wallpaper"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "图片标题", name: "title", widget: "string", required: true}
      - {label: "子分类", name: "category", widget: "select", options: ["自然风景", "动漫", "城市夜景"], required: true}
      - {label: "上传图片", name: "image", widget: "image", required: true}
  - name: "avatar"
    label: "个性头像"
    folder: "_avatar"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "图片标题", name: "title", widget: "string", required: true}
      - {label: "子分类", name: "category", widget: "select", options: ["卡通", "写实", "氛围感"], required: true}
      - {label: "上传图片", name: "image", widget: "image", required: true}
